#!/bin/sh
set -eu

# Archive metadata, imported media and SQLite state are private by default.
umask 077

case "${APP_BIND_ADDRESS:-127.0.0.1}" in
  127.0.0.1|::1) ;;
  *) echo "APP_BIND_ADDRESS must remain loopback-only" >&2; exit 1 ;;
esac

if [ "${TMPDIR:-}" = "/app/data/provider-staging/.runtime-tmp" ]; then
  rm -rf -- /app/data/provider-staging/.runtime-tmp
  mkdir -p /app/data/provider-staging/.runtime-tmp
  chmod 0700 /app/data/provider-staging/.runtime-tmp
fi

# HTTP Provider staging is SeeU-owned and non-canonical. A process restart means
# no task can still own these directories, so remove only the names generated by
# backend/app/provider.py and leave imports or unrelated paths untouched.
for staging_path in /app/data/provider-staging/http-*; do
  if [ -d "$staging_path" ]; then
    rm -rf -- "$staging_path"
  fi
done

exec "$@"
